# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nutritec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # 1. Configurar Node.js en la máquina virtual
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 2. Crear el archivo .env, instalar dependencias y compilar el React
      - name: npm install and build with env variables
        run: |
          # Creamos el archivo .env en caliente dentro de la carpeta del frontend
          echo "REACT_APP_API_URL=https://nutritec-api-dkgtbsfbgceue7cm.westus3-01.azurewebsites.net/api" > .env
          
          npm install
          # Desactivamos CI=false para que los warnings de ESLint no tiren abajo el build
          CI=false npm run build --if-present
        working-directory: frontend/web/client

      # 3. Subir únicamente la carpeta compilada (build) como artefacto
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/web/client/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      # 4. Descargar los archivos estáticos de la compilación
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./build
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7192E6290DB84A869D394B256971E9CB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9BC42333377244958439B96DAE1E11F2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD14913A98214D898659ACD01631214A }}

      # 5. Desplegar los archivos finales al App Service de Azure
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nutritec'
          slot-name: 'Production'
          package: ./build